version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8087:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload